### ISSUE TITLE
Tanvi feedback

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/paranoidpanda#2]
Feedback from @TanviHacks
## UX
- [ ] The UI for the descriptions is sometimes a little slow to respond.  When you cycle from High to Medium, it takes a second for the text to update.  Not sure if there is a way to make the text update faster
- [ ] Color the background of Low/Medium/High.  This way you can also see that they are each different buttons than it is with one background color.
- [x] The mask looks nice, but we have to be careful not to confuse this with Private Browsing Mode.  Or tracking protection (shield).  The mask is fine for now, but perhaps Bram may have some ideas on another icon we could use. Raised as #3
- [ ] The text descriptions for High says:  "High chance of breaking many sites. Disables prediction of URLs and low grade certs along with features which are easy to track users."
  I'm not sure exactly what this means.  We should talk about the prefs changed and then update the text.
## Prefs

There are a lot of prefs are your etherpad!  Nice job hunting these down.  I'm not sure what they all are, so maybe we can meet to go over that sometime.  The difference between medium and high is substantial, so I wonder if it is worth having another value.  So we could do a few things.
- [ ] We could have 4 levels, 1-4 where 1 is regular firefox (all defaults) and 4 is Paranoid.
- [ ] Or we could have 3 levels, where 1 is called low (but sets all the prefs set in medium right now), 2 is called medium (and sets all the prefs in medium right now plus some of the ones in paranoid), and 3 is paranoid.  In addition to the 3 levels we could include a button in the drop down that says "browse with regular firefox settings" or something like that.  Or it could say "disable secure fox" and that would put you in regular mode.  You could also
- [ ] We could have 4 levels and call the first level "Disable secure fox", the second one "Low", third "Medium", forth "Paranoid", all on the same slider.
## Code Questions
- [x] What is the path for users who uninstall or disable the addon?  Can we change all prefs back on disable or uninstall?  If users uninstall the addon after they have set security "Paranoid" and then not being able to recover and use broken webpages. Raised as #4
- [x] Is tracking protection on globally in low mode?  I'm in low mode and tracking protection is enabled on cnn.com.  Looking at your etherpad, it shows that all prefs have default values.  Maybe all prefs except the tracking protection one?   I also see that "always use private browsing mode is checked" and accept third party cookies is only accepted from visited.  Maybe the switch from medium to low isn't working properly? Raised as #5

**Comment by jonathanKingston** [comment]
> The mask looks nice, but we have to be careful not to confuse this with Private Browsing Mode. Or tracking protection (shield). The mask is fine for now, but perhaps Bram may have some ideas on another icon we could use.

Yeah it was a result of me playing about, I thought the dev icon you suggested would be more confusing etc. As you mention if this project has legs a real identity for it would be important.

**Comment by grahamperrin** [comment]
I know, not recent, but this sort of stuff interests me. 

Where best, in a Mozilla (or multi-organisational) area, to track notions of best practice/plain English when aiming to convey things such as "High chance of breaking many sites …"? (Any pointers?) 

TIA
